# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License
os:
  - linux

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install scipy
  - pip install numpy
  - pip install pandas
  - pip install dill
  - pip install scikit-learn
  - pip install hyperactive
  - pip install packaging
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install .

script:
  - pytest --cov=optimization_metadata/ -p no:warnings

after_success:
  - coveralls
